#!/bin/sh
#
# Copyright (C) 2015 InMotion Software
#

. /lib/functions/uci-defaults.sh

# Set the hostname for the gateway
uci batch <<EOF
set system.@system[0].hostname='reefaccess'
EOF
uci commit system


exit 0
