#!/bin/sh
#
# Copyright (C) 2015 InMotion Software
#

. /lib/functions/uci-defaults.sh

# Use the last 3 bytes of the mac address for use in SSID naming
device_id=$(ifconfig eth0 | awk '/HWaddr/ { print $5 }' | sed s/://g | head -c -7)
# Use random number for use in SSID naming
#device_id=$(head /dev/urandom | tr -dc "123456789" | head -c4)

###############################################################################
#
# inm_ucidef_languest_set_network()
#
# Creates the "languest" network interface.
#
###############################################################################
inm_ucidef_languest_set_network() {

# Create the "languest" interface.
uci batch <<EOF
set network.languest='interface'
set network.languest.type='bridge'
set network.languest.proto='static'
set network.languest.ipaddr='192.168.8.1'
set network.languest.netmask='255.255.252.0'
EOF

uci commit network
}


###############################################################################
#
# inm_ucidef_languest_set_dhcp()
#
# Creates the "languest" dhcp.
#
###############################################################################
inm_ucidef_languest_set_dhcp() {

uci batch <<EOF
set dhcp.languest='dhcp'
set dhcp.languest.start='100'
set dhcp.languest.leasetime='12h'
set dhcp.languest.limit='350'
set dhcp.languest.interface='languest'
EOF

uci commit dhcp
}


###############################################################################
#
# inm_ucidef_languest_set_wireless()
#
# Creates the "languest" wireless interfaces.
#
###############################################################################
inm_ucidef_languest_set_wireless() {

# radio0 - lan
uci batch <<EOF
set wireless.@wifi-iface[0]=wifi-iface
set wireless.@wifi-iface[0].device='radio0'
set wireless.@wifi-iface[0].network='lan'
set wireless.@wifi-iface[0].mode='ap'
set wireless.@wifi-iface[0].ssid='REEF-${device_id}-Instr-Ch1'
set wireless.@wifi-iface[0].encryption='psk'
set wireless.@wifi-iface[0].key='treehouse'
EOF

# radio1 - lan
uci batch <<EOF
set wireless.@wifi-iface[1]=wifi-iface
set wireless.@wifi-iface[1].device='radio1'
set wireless.@wifi-iface[1].network='lan'
set wireless.@wifi-iface[1].mode='ap'
set wireless.@wifi-iface[1].ssid='REEF-${device_id}-Instr-Ch2'
set wireless.@wifi-iface[1].encryption='psk'
set wireless.@wifi-iface[1].key='treehouse'
EOF

# radio0 - languest
uci batch <<EOF
add wireless wifi-iface
set wireless.@wifi-iface[-1].device='radio0'
set wireless.@wifi-iface[-1].network='languest'
set wireless.@wifi-iface[-1].mode='ap'
set wireless.@wifi-iface[-1].ssid='REEF-${device_id}-Stdnt-Ch1'
set wireless.@wifi-iface[-1].encryption='psk'
set wireless.@wifi-iface[-1].key='treehouse'
EOF

# radio - languest
uci batch <<EOF
add wireless wifi-iface
set wireless.@wifi-iface[-1].device='radio1'
set wireless.@wifi-iface[-1].network='languest'
set wireless.@wifi-iface[-1].mode='ap'
set wireless.@wifi-iface[-1].ssid='REEF-${device_id}-Stdnt-Ch2'
set wireless.@wifi-iface[-1].encryption='psk'
set wireless.@wifi-iface[-1].key='treehouse'
EOF

uci commit wireless
}


###############################################################################
#
# inm_ucidef_languest_set_firewall()
#
# Creates the "languest" firewall rules.
#
###############################################################################
inm_ucidef_languest_set_firewall() {

# Create the languest zone
uci batch <<EOF
delete firewall.zone_languest
set firewall.zone_languest=zone
set firewall.zone_languest.name='languest'
set firewall.zone_languest.input='ACCEPT'
set firewall.zone_languest.forward='REJECT'
set firewall.zone_languest.output='ACCEPT'
set firewall.zone_languest.network='languest'
EOF

# Forward things from languest to wan
uci batch <<EOF
delete firewall.forwarding_languest_wan
set firewall.forwarding_languest_wan=forwarding
set firewall.forwarding_languest_wan.src='languest'
set firewall.forwarding_languest_wan.dest='wan'
EOF

# Allow DNS on languest
uci batch <<EOF
delete firewall.rule_languest_dns_accept
set firewall.rule_languest_dns_accept=rule
set firewall.rule_languest_dns_accept.name='languest: dns accept'
set firewall.rule_languest_dns_accept.enabled='1'
set firewall.rule_languest_dns_accept.src='languest'
set firewall.rule_languest_dns_accept.dest_port='53'
set firewall.rule_languest_dns_accept.proto='tcp udp'
set firewall.rule_languest_dns_accept.target='ACCEPT'
EOF

# Allow DHCP on languest
uci batch <<EOF
delete firewall.rule_languest_dhcp_accept
set firewall.rule_languest_dhcp_accept=rule
set firewall.rule_languest_dhcp_accept.name='languest: dhcp accept'
set firewall.rule_languest_dhcp_accept.enabled='1'
set firewall.rule_languest_dhcp_accept.src='languest'
set firewall.rule_languest_dhcp_accept.dest_port='67-68'
set firewall.rule_languest_dhcp_accept.proto='udp'
set firewall.rule_languest_dhcp_accept.target='ACCEPT'
EOF

# Drop everything from languest to lan
uci batch <<EOF
delete firewall.rule_languest_to_lan_all_drop
set firewall.rule_languest_to_lan_all_drop=rule
set firewall.rule_languest_to_lan_all_drop.name='languest: lan all drop'
set firewall.rule_languest_to_lan_all_drop.enabled='1'
set firewall.rule_languest_to_lan_all_drop.src='languest'
set firewall.rule_languest_to_lan_all_drop.dest='lan'
set firewall.rule_languest_to_lan_all_drop.proto='all'
set firewall.rule_languest_to_lan_all_drop.target='DROP'
EOF

uci commit firewall
}




###############################################################################
#
# Main entry point
#
###############################################################################

# Change the default "lan" ip address
uci set network.lan.ipaddr=192.168.4.1
uci commit network

# Create the "languest" interface/wifi
inm_ucidef_languest_set_network
inm_ucidef_languest_set_dhcp
inm_ucidef_languest_set_wireless
inm_ucidef_languest_set_firewall

exit 0
