#!/bin/sh
#
# Copyright (C) 2015 InMotion Software
#

. /lib/functions/uci-defaults.sh


###############################################################################
#
# inm_ucidef_squid_nontransparent()
#
# Creates the HTTP server to serve up the proxy.pac file
#
###############################################################################
inm_ucidef_squid_nontransparent() {


#
# Create an alias so that clients can find the proxy wpad.dat file so that they can auto configure themselves
#
uci batch <<EOF
delete dhcp.domain_lan_wpad
set dhcp.domain_lan_wpad=domain
set dhcp.domain_lan_wpad.name='wpad'
set dhcp.domain_lan_wpad.ip='192.168.4.1'
EOF

#uci batch <<EOF
#delete dhcp.domain_languest_wpad
#set dhcp.domain_languest_wpad=domain
#set dhcp.domain_languest_wpad.name='wpad'
#set dhcp.domain_languest_wpad.ip='192.168.8.1'
#EOF

uci commit dhcp


#
# Create the DHCP options
#
uci batch <<EOF
set dhcp.lan.dhcp_option='252,http://reefaccess/wpad.dat'
set dhcp.lan_guest.dhcp_option='252,http://reefaccess/wpad.dat'
EOF
uci commit dhcp


#
# Link the proxy.pac to wpad.dat and wpad.da
#
ln -s /www/proxy.pac /www/wpad.dat
ln -s /www/proxy.pac /www/wpad.da

ln -s /www_file_svr/proxy.pac /www_file_svr/wpad.dat
ln -s /www_file_svr/proxy.pac /www_file_svr/wpad.da


#
# Move the normal web server to port 8080 and 8443
# and bind it to the 'lan' subnet only
#
uci batch <<EOF
set uhttpd.main.listen_http='0.0.0.0:8080 [::]:8080'
set uhttpd.main.listen_https='0.0.0.0:8443 [::]:8443'
EOF
uci commit uhttpd


#
# Create firewall rules to allow the 'luci' web server from 'lan' only
#

# Allow from 'lan'
uci batch <<EOF
delete firewall.rule_mainweb_lan_accept
set firewall.rule_mainweb_lan_accept=rule
set firewall.rule_mainweb_lan_accept.src='lan'
set firewall.rule_mainweb_lan_accept.name='MainWeb: lan accept'
set firewall.rule_mainweb_lan_accept.dest_port='8080 8443'
set firewall.rule_mainweb_lan_accept.target='ACCEPT'
set firewall.rule_mainweb_lan_accept.proto='tcp'
EOF
uci commit firewall

# Reject from all
uci batch <<EOF
delete firewall.rule_mainweb_all_reject
set firewall.rule_mainweb_all_reject=rule
set firewall.rule_mainweb_all_reject.name='MainWeb: all reject'
set firewall.rule_mainweb_all_reject.dest_port='8080 8443'
set firewall.rule_mainweb_all_reject.target='REJECT'
set firewall.rule_mainweb_all_reject.proto='tcp'
EOF
uci commit firewall


#
# Create the web server that serves up the proxy.pac/wpad.dat file for automatic proxy configuration
#
uci batch <<EOF
set uhttpd.file_svr='uhttpd'
set uhttpd.file_svr.listen_http='0.0.0.0:80 [::]:80'
set uhttpd.file_svr.listen_https='0.0.0.0:443 [::]:443'
set uhttpd.file_svr.redirect_https='0'
set uhttpd.file_svr.home='/www_file_svr'
set uhttpd.file_svr.rfc1918_filter='1'
set uhttpd.file_svr.max_requests='3'
set uhttpd.file_svr.max_connections='100'
set uhttpd.file_svr.cert='/etc/uhttpd.crt'
set uhttpd.file_svr.key='/etc/uhttpd.key'
set uhttpd.file_svr.cgi_prefix='/cgi-bin'
set uhttpd.file_svr.script_timeout='60'
set uhttpd.file_svr.network_timeout='30'
set uhttpd.file_svr.http_keepalive='20'
set uhttpd.file_svr.tcp_keepalive='1'
set uhttpd.file_svr.ubus_prefix='/ubus'
EOF
uci commit uhttpd

# Reject from 'wan'
uci batch <<EOF
delete firewall.rule_filesvr_wan_reject
set firewall.rule_filesvr_wan_reject=rule
set firewall.rule_filesvr_wan_reject.src='wan'
set firewall.rule_filesvr_wan_reject.name='FileSvr: wan reject'
set firewall.rule_filesvr_wan_reject.dest_port='80 443'
set firewall.rule_filesvr_wan_reject.target='REJECT'
set firewall.rule_filesvr_wan_reject.proto='tcp'
EOF
uci commit firewall


#
# Create firewall rules to block access to normal HTTP and HTTPS from lan or lan_guest to WAN
#
uci batch <<EOF
delete firewall.rule_lan_to_wan_web
set firewall.rule_lan_to_wan_web=rule
set firewall.rule_lan_to_wan_web.src='lan'
set firewall.rule_lan_to_wan_web.dest='wan'
set firewall.rule_lan_to_wan_web.name='Proxy: lan to wan web reject'
set firewall.rule_lan_to_wan_web.dest_port='80 443'
set firewall.rule_lan_to_wan_web.target='REJECT'
set firewall.rule_lan_to_wan_web.proto='tcp'
EOF

uci batch <<EOF
delete firewall.rule_languest_to_wan_web
set firewall.rule_languest_to_wan_web=rule
set firewall.rule_languest_to_wan_web.src='lan_guest'
set firewall.rule_languest_to_wan_web.dest='wan'
set firewall.rule_languest_to_wan_web.name='Proxy: lan_guest to wan web reject'
set firewall.rule_languest_to_wan_web.dest_port='80 443'
set firewall.rule_languest_to_wan_web.target='REJECT'
set firewall.rule_languest_to_wan_web.proto='tcp'
EOF


uci commit firewall
}


###############################################################################
#
# Main entry point
#
###############################################################################

uci batch <<EOF
set squid.squid.visible_hostname='reefaccess'
EOF
uci commit squid

## Set the "squid" transparent proxy settings
#inm_ucidef_squid_transparent_firewall
#inm_ucidef_squid_transparent_ssl

# Set the "squid" nontransparent proxy settings
inm_ucidef_squid_nontransparent

exit 0
