#!/bin/sh
#
# Copyright (C) 2015 InMotion Software
#

. /lib/functions/uci-defaults.sh


###############################################################################
#
# inm_ucidef_squid_nontransparent()
#
# Creates the HTTP server to serve up the proxy.pac file
#
###############################################################################
inm_ucidef_squid_nontransparent() {


#
# Create an alias so that clients can find the proxy wpad.dat file so that they can auto configure themselves
#
uci batch <<EOF
delete dhcp.domain_lan_wpad
set dhcp.domain_lan_wpad=domain
set dhcp.domain_lan_wpad.name='wpad'
set dhcp.domain_lan_wpad.ip='192.168.4.1'
EOF
uci commit dhcp


#
# Create the DHCP options
#
uci batch <<EOF
set dhcp.lan.dhcp_option='252,http://reefaccess/wpad.dat'
set dhcp.languest.dhcp_option='252,http://reefaccess/wpad.dat'
EOF
uci commit dhcp


#
# Link the proxy.pac to wpad.dat and wpad.da
#
ln -s /www_file_svr/proxy.pac /www_file_svr/wpad.dat
ln -s /www_file_svr/proxy.pac /www_file_svr/wpad.da


#
# Move the normal web server to port 8080 and 8443
#
uci batch <<EOF
set uhttpd.main.listen_http='0.0.0.0:8080 [::]:8080'
set uhttpd.main.listen_https='0.0.0.0:8443 [::]:8443'
EOF
uci commit uhttpd


#
# Create firewall rules to allow the 'luci' web server from 'lan' only
#

# Allow from 'lan'
uci batch <<EOF
delete firewall.rule_mainweb_lan_accept
set firewall.rule_mainweb_lan_accept=rule
set firewall.rule_mainweb_lan_accept.src='lan'
set firewall.rule_mainweb_lan_accept.name='MainWeb: lan accept'
set firewall.rule_mainweb_lan_accept.dest_port='8080 8443'
set firewall.rule_mainweb_lan_accept.target='ACCEPT'
set firewall.rule_mainweb_lan_accept.proto='tcp'
EOF
uci commit firewall

#
# Create the web server that serves up the proxy.pac/wpad.dat file for automatic proxy configuration
#
uci batch <<EOF
set uhttpd.file_svr='uhttpd'
set uhttpd.file_svr.listen_http='0.0.0.0:80 [::]:80'
set uhttpd.file_svr.listen_https='0.0.0.0:443 [::]:443'
set uhttpd.file_svr.redirect_https='0'
set uhttpd.file_svr.home='/www_file_svr'
set uhttpd.file_svr.rfc1918_filter='1'
set uhttpd.file_svr.max_requests='3'
set uhttpd.file_svr.max_connections='100'
set uhttpd.file_svr.cert='/etc/uhttpd.crt'
set uhttpd.file_svr.key='/etc/uhttpd.key'
set uhttpd.file_svr.cgi_prefix='/cgi-bin'
set uhttpd.file_svr.script_timeout='60'
set uhttpd.file_svr.network_timeout='30'
set uhttpd.file_svr.http_keepalive='20'
set uhttpd.file_svr.tcp_keepalive='1'
set uhttpd.file_svr.ubus_prefix='/ubus'
EOF
uci commit uhttpd

# Allow access to the wpad webserver from lan
uci batch <<EOF
delete firewall.rule_proxy_wpad_webserver_lan_accept
set firewall.rule_proxy_wpad_webserver_lan_accept=rule
set firewall.rule_proxy_wpad_webserver_lan_accept.name='Proxy: wpad webserver: lan accept'
set firewall.rule_proxy_wpad_webserver_lan_accept.src='lan'
set firewall.rule_proxy_wpad_webserver_lan_accept.dest_port='80 443'
set firewall.rule_proxy_wpad_webserver_lan_accept.target='ACCEPT'
set firewall.rule_proxy_wpad_webserver_lan_accept.proto='tcp'
EOF

# Allow access to the wpad webserver from languest
uci batch <<EOF
delete firewall.rule_proxy_wpad_webserver_languest_accept
set firewall.rule_proxy_wpad_webserver_languest_accept=rule
set firewall.rule_proxy_wpad_webserver_languest_accept.name='Proxy: wpad webserver: languest accept'
set firewall.rule_proxy_wpad_webserver_languest_accept.src='languest'
set firewall.rule_proxy_wpad_webserver_languest_accept.dest_port='80 443'
set firewall.rule_proxy_wpad_webserver_languest_accept.target='ACCEPT'
set firewall.rule_proxy_wpad_webserver_languest_accept.proto='tcp'
EOF

# Allow access to the proxy server from lan
uci batch <<EOF
delete firewall.rule_proxy_lan_accept
set firewall.rule_proxy_lan_accept=rule
set firewall.rule_proxy_lan_accept.name='Proxy: lan accept'
set firewall.rule_proxy_lan_accept.src='lan'
set firewall.rule_proxy_lan_accept.dest_port='3128'
set firewall.rule_proxy_lan_accept.target='ACCEPT'
set firewall.rule_proxy_lan_accept.proto='tcp'
EOF

# Allow access to the proxy server from languest
uci batch <<EOF
delete firewall.rule_proxy_languest_accept
set firewall.rule_proxy_languest_accept=rule
set firewall.rule_proxy_languest_accept.name='Proxy: languest accept'
set firewall.rule_proxy_languest_accept.src='languest'
set firewall.rule_proxy_languest_accept.dest_port='3128'
set firewall.rule_proxy_languest_accept.target='ACCEPT'
set firewall.rule_proxy_languest_accept.proto='tcp'
EOF

#
# WORKAROUND: Due to WebSockets not going through the proxy...
# Create firewall rules to allow access to normal HTTP and HTTPS from lan or languest to WAN
# targeting .reef-education.com
#
# api-dev.reef-education.com    107.20.8.157
# api-qa.reef-education.com     54.237.128.85
# api-beta.reef-education.com   54.229.9.24
# api.reef-education.com        54.72.117.52
#
uci batch <<EOF
delete firewall.rule_proxy_lan_to_wan_web_reef
set firewall.rule_proxy_lan_to_wan_web_reef=rule
set firewall.rule_proxy_lan_to_wan_web_reef.src='lan'
set firewall.rule_proxy_lan_to_wan_web_reef.dest='wan'
set firewall.rule_proxy_lan_to_wan_web_reef.dest_ip='107.20.8.157 54.237.128.85 54.229.9.24 54.72.117.52'
set firewall.rule_proxy_lan_to_wan_web_reef.name='Proxy: lan to wan web .reef-education.com accept'
set firewall.rule_proxy_lan_to_wan_web_reef.dest_port='80 443'
set firewall.rule_proxy_lan_to_wan_web_reef.target='ACCEPT'
set firewall.rule_proxy_lan_to_wan_web_reef.proto='tcp'
EOF

uci batch <<EOF
delete firewall.rule_proxy_languest_to_wan_web_reef
set firewall.rule_proxy_languest_to_wan_web_reef=rule
set firewall.rule_proxy_languest_to_wan_web_reef.src='languest'
set firewall.rule_proxy_languest_to_wan_web_reef.dest='wan'
set firewall.rule_proxy_languest_to_wan_web_reef.dest_ip='107.20.8.157 54.237.128.85 54.229.9.24 54.72.117.52'
set firewall.rule_proxy_languest_to_wan_web_reef.name='Proxy: languest to wan web .reef-education.com accept'
set firewall.rule_proxy_languest_to_wan_web_reef.dest_port='80 443'
set firewall.rule_proxy_languest_to_wan_web_reef.target='ACCEPT'
set firewall.rule_proxy_languest_to_wan_web_reef.proto='tcp'
EOF


#
# Create firewall rules to block access to normal HTTP and HTTPS from lan or languest to WAN
#
uci batch <<EOF
delete firewall.rule_proxy_lan_to_wan_web
set firewall.rule_proxy_lan_to_wan_web=rule
set firewall.rule_proxy_lan_to_wan_web.src='lan'
set firewall.rule_proxy_lan_to_wan_web.dest='wan'
set firewall.rule_proxy_lan_to_wan_web.name='Proxy: lan to wan web reject'
set firewall.rule_proxy_lan_to_wan_web.dest_port='80 443'
set firewall.rule_proxy_lan_to_wan_web.target='REJECT'
set firewall.rule_proxy_lan_to_wan_web.proto='tcp'
EOF

uci batch <<EOF
delete firewall.rule_proxy_languest_to_wan_web
set firewall.rule_proxy_languest_to_wan_web=rule
set firewall.rule_proxy_languest_to_wan_web.src='languest'
set firewall.rule_proxy_languest_to_wan_web.dest='wan'
set firewall.rule_proxy_languest_to_wan_web.name='Proxy: languest to wan web reject'
set firewall.rule_proxy_languest_to_wan_web.dest_port='80 443'
set firewall.rule_proxy_languest_to_wan_web.target='REJECT'
set firewall.rule_proxy_languest_to_wan_web.proto='tcp'
EOF

#
# Create firewall rules to block access to normal QUIC (Quick UDP Internet Connections) from lan or languest to WAN
#
uci batch <<EOF
delete firewall.rule_proxy_lan_to_wan_quic
set firewall.rule_proxy_lan_to_wan_quic=rule
set firewall.rule_proxy_lan_to_wan_quic.src='lan'
set firewall.rule_proxy_lan_to_wan_quic.dest='wan'
set firewall.rule_proxy_lan_to_wan_quic.name='Proxy: lan to wan quic reject'
set firewall.rule_proxy_lan_to_wan_quic.dest_port='443'
set firewall.rule_proxy_lan_to_wan_quic.target='REJECT'
set firewall.rule_proxy_lan_to_wan_quic.proto='udp'
EOF

uci batch <<EOF
delete firewall.rule_proxy_languest_to_wan_quic
set firewall.rule_proxy_languest_to_wan_quic=rule
set firewall.rule_proxy_languest_to_wan_quic.src='languest'
set firewall.rule_proxy_languest_to_wan_quic.dest='wan'
set firewall.rule_proxy_languest_to_wan_quic.name='Proxy: languest to wan quic reject'
set firewall.rule_proxy_languest_to_wan_quic.dest_port='443'
set firewall.rule_proxy_languest_to_wan_quic.target='REJECT'
set firewall.rule_proxy_languest_to_wan_quic.proto='udp'
EOF


uci commit firewall
}


###############################################################################
#
# Main entry point
#
###############################################################################

uci batch <<EOF
set squid.squid.visible_hostname='reefaccess'
EOF
uci commit squid

# Set the "squid" nontransparent proxy settings
inm_ucidef_squid_nontransparent

exit 0
